## 라이브러리
```{r}
library(forecast)
library(ggplot2)
library(dplyr)
library(gridExtra)

```

## 함수
```{r}
air <- function(x){
  y<-read.csv(x, header = T, stringsAsFactors = F)
  y$지역 <- substr(y$지역, 1,2)
  y <- y[y$지역 =="서울", ]
  y <- y[ , c("측정일시", "주소", "PM10")]    # 필요한 열만 추출
  colnames(y) <- c("월", "구", "미세먼지")

  # 날짜 변환
  y$월 <- substr(y$월, 1, 6)
  y$월 <- as.integer(y$월)
  
  # 구만 뽑기
  gu<-strsplit(y$구, " ")
  for(i in 1:length(gu)){
            y$구[i] <-  gu[[i]][2]
  }
  
  # 구 데이터 정제
  y$구 <- gsub("강서로45다길", "강서구",y$구)
  y$구 <- gsub("강서로", "강서구",y$구)
  
  df<-aggregate(미세먼지~월+구,y, mean)
  return(df)
}

```

## 데이터 합치기
```{r}
  y14_1<-air("c:/r/미세먼지/2014년 1분기.csv")
  y14_2<-air("c:/r/미세먼지/2014년 2분기.csv")
  y14_3<-air("c:/r/미세먼지/2014년 3분기.csv")
  y14_4<-air("c:/r/미세먼지/2014년 4분기.csv")
  y15_1<-air("c:/r/미세먼지/2015년 1분기.csv")
  y15_2<-air("c:/r/미세먼지/2015년 2분기.csv")
  y15_3<-air("c:/r/미세먼지/2015년 3분기.csv")
  y15_4<-air("c:/r/미세먼지/2015년 4분기.csv")
  y16_1<-air("c:/r/미세먼지/2016년 1분기.csv")
  y16_2<-air("c:/r/미세먼지/2016년 2분기.csv")
  y16_3<-air("c:/r/미세먼지/2016년 3분기.csv")
  y16_4<-air("c:/r/미세먼지/2016년 4분기.csv")
  y17_1<-air("c:/r/미세먼지/2017년 1분기.csv")
  y17_2<-air("c:/r/미세먼지/2017년 2분기.csv")
  y17_3<-air("c:/r/미세먼지/2017년 3분기.csv")
  
  test_data <- rbind(y14_1, y14_2, y14_3, y14_4,
                     y15_1, y15_2, y15_3, y15_4,
                     y16_1, y16_2, y16_3, y16_4)
  
  real_data <- rbind(y17_1, y17_2, y17_3)

  
  test_data <- arrange(test_data, 구, 월)
  real_data <- arrange(real_data, 구, 월)
  
  
```

```{r}

#### 2017년도 각 구별 1-9월 미세먼지 예측값 (Arima 모델 이용)
df_pred_total <- data.frame(월= NULL, 구=NULL, 예측값=NULL)
seoul_gu <- unique(test_data$구)
for (i in seoul_gu){

  test_gu <- test_data[test_data$구 ==i, c("미세먼지")]
  ts_gu <- ts(test_gu , frequency = 12 ,start = 2014)
  gnBest <- auto.arima(x= ts_gu)
  fore<- forecast(object=gnBest, h = 9)
  pr <- as.vector(fore$mean)

  df_pred <- data.frame(
    월 = as.character(rep(1:9)),
    구 = rep(i, each=9),
    예측값 = pr )

  df_pred_total <- rbind(df_pred_total, df_pred)
}
smoke_pred<-ggplot(df_pred_total, aes(x=월, y=예측값, group=구, col=구))+
              geom_line()+
                facet_wrap(~구)+
                  labs(title="2017년도 각 구별 1-9월 미세먼지 예측값")

smoke_pred_1<-ggplot(df_pred_total, aes(x=월, y=예측값, group=구, col=구))+
              geom_line()+
                  labs(title="2017년도 각 구별 1-9월 미세먼지 예측값")

#### 2017년도 각 구별 1-9월 미세먼지 월

real_data$월<- gsub( 20170, "",real_data$월)
smoke_real<- ggplot(real_data, aes(x=월, y=미세먼지, group=구, col=구))+
              geom_line()+
                facet_wrap(~구)+
                  labs(title="2017년도 각 구별 1-9월 미세먼지 실제값")

smoke_real_1<- ggplot(real_data, aes(x=월, y=미세먼지, group=구, col=구))+
                  geom_line()+
                    labs(title="2017년도 각 구별 1-9월 미세먼지 실제값")

### 2017년도 각 구별 1-9월 미세먼지 예측 오차

differ <- df_pred_total$예측값 - real_data$미세먼지


df_differ <- data.frame(월= real_data$월,
             구 = real_data$구,
             차이값= differ)

  
smoke_differ  <- ggplot(df_differ, aes(x=월, y=차이값, group=구, col=구))+
                  geom_line()+
                    facet_wrap(~구)+
                      labs(title="2017년도 각 구별 1-9월 미세먼지 예측 오차")

smoke_differ_1<-ggplot(df_differ, aes(x=월, y=차이값, group=구, col=구))+
                 geom_line()+
                  labs(title="2017년도 각 구별 1-9월 미세먼지 예측 오차(예측값 - 실제값)")

# 구별 분포도
smoke_pred
smoke_real
smoke_differ

## 하나의 분포도
smoke_pred_1
smoke_real_1
smoke_differ_1
```


# 시간대별 함수
```{r}

## 시간대별 미세먼지 함수
air_d <- function(x){
  y<-read.csv(x, header = T, stringsAsFactors = F)
  y$지역 <- substr(y$지역, 1,2)
  y <- y[y$지역 =="서울", ]
  y <- y[ , c("측정일시", "주소", "PM10")]    # 필요한 열만 추출
  colnames(y) <- c("날짜", "구", "미세먼지")

  # 날짜 변환
  y$날짜 <- as.integer(y$날짜)
  
  # 구만 뽑기
  gu<-strsplit(y$구, " ")
  for(i in 1:length(gu)){
            y$구[i] <-  gu[[i]][2]
  }
  
  # 구 데이터 정제
  y$구 <- gsub("강서로45다길", "강서구",y$구)
  y$구 <- gsub("강서로", "강서구",y$구)
  
  df<-aggregate(미세먼지~날짜+구,y, mean)
  return(df)
}


```

## 데이터 합치기
```{r}
  y14_1_d<-air_d("c:/r/미세먼지/2014년 1분기.csv")
  y14_2_d<-air_d("c:/r/미세먼지/2014년 2분기.csv")
  y14_3_d<-air_d("c:/r/미세먼지/2014년 3분기.csv")
  y14_4_d<-air_d("c:/r/미세먼지/2014년 4분기.csv")
  y15_1_d<-air_d("c:/r/미세먼지/2015년 1분기.csv")
  y15_2_d<-air_d("c:/r/미세먼지/2015년 2분기.csv")
  y15_3_d<-air_d("c:/r/미세먼지/2015년 3분기.csv")
  y15_4_d<-air_d("c:/r/미세먼지/2015년 4분기.csv")
  y16_1_d<-air_d("c:/r/미세먼지/2016년 1분기.csv")
  y16_2_d<-air_d("c:/r/미세먼지/2016년 2분기.csv")
  y16_3_d<-air_d("c:/r/미세먼지/2016년 3분기.csv")
  y16_4_d<-air_d("c:/r/미세먼지/2016년 4분기.csv")
  
  
  test_data_d <- rbind(y14_1_d, y14_2_d, y14_3_d, y14_4_d,
                     y15_1_d, y15_2_d, y15_3_d, y15_4_d,
                     y16_1_d, y16_2_d, y16_3_d, y16_4_d)
                     
  
  test_data_d <- arrange(test_data_d, 구, 날짜)
  

```

```{r}
## 가독성을 위해서 시간, 일 단위 제거
test_data_d$날짜 <- substr(test_data_d$날짜, 1, 6)

max(test_data_d$미세먼지)  # 미세먼지 최대수치는 1033
min(test_data_d$미세먼지)  # 미세먼지 최소 수치는 1

## 미세먼지 200이상을 이상값이라고 가정하고 200이상인 수치만 뽑기
df_200 <- test_data_d[test_data_d$미세먼지 >=200, ]

## 미세먼지수치 등급 매기기
df_200$미세먼지수치 <-ifelse( df_200$미세먼지>=200 & df_200$미세먼지 < 500,"200~400",
                ifelse( df_200$미세먼지>=500 & df_200$미세먼지 < 800, "500~700",
                  ifelse( df_200$미세먼지>=800, "800~1033" , df_200$미세먼지)))     


df_200$날짜 <- substr(df_200$날짜, 5, 6)
df_200$미세먼지 <- 1


## 월별 미세먼지 건수 
df_200_total<- aggregate(미세먼지~미세먼지수치+날짜, df_200, sum)
colnames(df_200_total) <- c("미세먼지수치", "월", "건수")

ggplot(df_200_total, aes(x=월, y=건수, fill=미세먼지수치))+
  geom_bar(stat="identity")+
     geom_text(aes(label = 건수 ),
               position = position_stack(vjust=0.5) )

####각 구별 월 미세먼지 건수
df_200_gu<- aggregate(미세먼지~미세먼지수치+날짜+구, df_200, sum)
colnames(df_200_gu) <- c("미세먼지수치", "월","구","건수")

ggplot(df_200_gu, aes(x=월, y=건수, group=구,fill=미세먼지수치))+
  geom_bar(stat="identity")+
   facet_wrap(~구)
     
####
위에 분석한 결과를 보면, 4,5,8월의 오차가 큼
 그래서 4,5,8월 raw데이터의 미세먼지 수치가 높을거란 가정을 하고 월별로 미세먼치 수치가  높은 건수를 분석함
 분결 결과, 수치가 높은 미세먼지가 많이 분포한 달은 2월이었고 3월이 두번째, 4월이 세번째였음. 8월은 가장 낮음.
 가장 수치가 많았던 2월은 오차가 거의 없었기 때문에 이 가정은 틀린것으로 판단
 따라서 과도하게 높게 측정된 미세먼지 수치의 raw 데이터가 분석 모델에 영향을 주기는 힘들거라 판단.
 그래서 오차의 원인은 raw데이터가 아니라 arima 모델의 한계라고 생각.


```

### 시간대별 미세먼지 수치 구하기

#시간대별 함수
```{r}

air_h <- function(x){
  y<-read.csv(x, header = T, stringsAsFactors = F)
  y$지역 <- substr(y$지역, 1,2)
  y <- y[y$지역 =="서울", ]
  y <- y[ , c("측정일시", "주소", "PM10")]    # 필요한 열만 추출
  colnames(y) <- c("시간", "구", "미세먼지")

  # 시간 변환
  y$시간 <- as.integer(substr(y$시간, 9, 10))
  
  # 구만 뽑기
  gu<-strsplit(y$구, " ")
  for(i in 1:length(gu)){
            y$구[i] <-  gu[[i]][2]
  }
  
  # 구 데이터 정제
  y$구 <- gsub("강서로45다길", "강서구",y$구)
  y$구 <- gsub("강서로", "강서구",y$구)
  
  df<-aggregate(미세먼지~시간+구,y, mean)
  return(df)
}


```

# 데이터 통합
```{r}
  y14_1_h<-air_h("c:/r/미세먼지/2014년 1분기.csv")
  y14_2_h<-air_h("c:/r/미세먼지/2014년 2분기.csv")
  y14_3_h<-air_h("c:/r/미세먼지/2014년 3분기.csv")
  y14_4_h<-air_h("c:/r/미세먼지/2014년 4분기.csv")
  y15_1_h<-air_h("c:/r/미세먼지/2015년 1분기.csv")
  y15_2_h<-air_h("c:/r/미세먼지/2015년 2분기.csv")
  y15_3_h<-air_h("c:/r/미세먼지/2015년 3분기.csv")
  y15_4_h<-air_h("c:/r/미세먼지/2015년 4분기.csv")
  y16_1_h<-air_h("c:/r/미세먼지/2016년 1분기.csv")
  y16_2_h<-air_h("c:/r/미세먼지/2016년 2분기.csv")
  y16_3_h<-air_h("c:/r/미세먼지/2016년 3분기.csv")
  y16_4_h<-air_h("c:/r/미세먼지/2016년 4분기.csv")
  y17_1_h<-air_h("c:/r/미세먼지/2017년 1분기.csv")
  y17_2_h<-air_h("c:/r/미세먼지/2017년 2분기.csv")
  y17_3_h<-air_h("c:/r/미세먼지/2017년 3분기.csv")
  
  data_h <-rbind(y14_1_h, y14_2_h, y14_3_h, y14_4_h,
                 y15_1_h, y15_2_h, y15_3_h, y15_4_h,
                 y16_1_h, y16_2_h, y16_3_h, y16_4_h,
                 y17_1_h, y17_2_h, y17_3_h)
 df_h <- aggregate(미세먼지~시간+구, data_h, mean)
 
 
  
```



# 각 구별 시간대 미세먼지 농도
```{r}
###
ggplot(df_h, aes(x=시간, y=미세먼지, group=구, col= 구))+
   geom_line()+
     facet_wrap(~구)+
       labs(title= "각 구별 시간대 미세먼지 농도")

###
ggplot(df_h, aes(x=시간, y=미세먼지, group=구, col= 구))+
   geom_line()+
       labs(title= "각 구별 시간대 미세먼지 농도")
 
```

