## 함수
```{r}
air <- function(x){
  y<-read.csv(x, header = T, stringsAsFactors = F)
  y$지역 <- substr(y$지역, 1,2)
  y <- y[y$지역 =="서울", ]
  y <- y[ , c("측정일시", "주소", "PM10")]    # 필요한 열만 추출
  colnames(y) <- c("날짜", "구", "미세먼지")

  # 날짜 변환
  y$날짜 <- substr(y$날짜, 1, 6)
  y$날짜 <- as.integer(y$날짜)
  
  # 구만 뽑기
  gu<-strsplit(y$구, " ")
  for(i in 1:length(gu)){
            y$구[i] <-  gu[[i]][2]
  }
  
  # 구 데이터 확인
  unique(y$구)                     
  y$구 <- gsub("강서로45다길", "강서구",y$구)
  
  
  df<-aggregate(미세먼지~날짜+구,y, mean)
  return(df)
  }
```

## 데이터 합치기
```{r}


  y14_1<-air("c:/r/미세먼지/2014년 1분기.csv")
  y14_2<-air("c:/r/미세먼지/2014년 2분기.csv")
  y14_3<-air("c:/r/미세먼지/2014년 3분기.csv")
  y14_4<-air("c:/r/미세먼지/2014년 4분기.csv")
  y15_1<-air("c:/r/미세먼지/2015년 1분기.csv")
  y15_2<-air("c:/r/미세먼지/2015년 2분기.csv")
  y15_3<-air("c:/r/미세먼지/2015년 3분기.csv")
  y15_4<-air("c:/r/미세먼지/2015년 4분기.csv")
  y16_1<-air("c:/r/미세먼지/2016년 1분기.csv")
  y16_2<-air("c:/r/미세먼지/2016년 2분기.csv")
  y16_3<-air("c:/r/미세먼지/2016년 3분기.csv")
  y16_4<-air("c:/r/미세먼지/2016년 4분기.csv")
  y17_1<-air("c:/r/미세먼지/2017년 1분기.csv")
  y17_2<-air("c:/r/미세먼지/2017년 2분기.csv")
  y17_3<-air("c:/r/미세먼지/2017년 3분기.csv")
  
  test_data <- rbind(y14_1, y14_2, y14_3, y14_4,
                     y15_1, y15_2, y15_3, y15_4,
                     y16_1, y16_2, y16_3, y16_4)
                     
  real_data <- rbind(y17_1, y17_2, y17_3)

```



```{r}
gn_test <- test_data[test_data$구 =="강남구", c("미세먼지")]
gn_real <- real_data[real_data$구 =="강남구", c("미세먼지")]

head(gn_test)

s <- min(test_data$날짜)
e <- max(test_data$날짜)

gn_ts <- ts(gn_test, frequency = 12 , start = 2014, end= 2016)
gn_test
gn_ts
plot(gn_ts)

```


```{r}
acf(gn_ts)
pacf(gn_ts)

```


```{r}
library(forecast)
gnBest <- auto.arima(x= gn_ts)
gnBest
acf(gnBest$residuals)
pacf(gnBest$residuals)

```


```{r}
coef(gnBest)
pred <- predict(gnBest, n.ahead = 30, se.fit = TRUE)
fore<- forecast(object=gnBest, h = 30)
plot(fore)

pred
gn_real[1:30]
```

